### ISSUE TITLE
invalid job spec

### ISSUE THREAD

**Issue by cppforlife** [Dynatrace/bosh-oneagent-release#11]
it appears that both job specs include `packages:  ` in both of the jobs. this translates into packages being `nil`; however, packages is expected to be an array of strings. this error causes bosh.io not to be able to pick new release.

cc @voelzmo

**Comment by arthfl** [comment]
Thanks for bringing this up!
Already merged the PR from @voelzmo and published a new release with the changes [v1.0.3](https://github.com/Dynatrace/bosh-oneagent-release/releases/tag/v1.0.3)
