### ISSUE TITLE
Error handling in pre-start leads to loss of valuable info.

### ISSUE THREAD

**Issue by Espe0n** [Dynatrace/bosh-oneagent-release#19]
Hi,
At the moment, the pre-start-Script calls the Installer without checking the Return code afterwards. 
(See https://github.com/Dynatrace/bosh-oneagent-release/blob/master/jobs/dynatrace-oneagent/templates/pre-start.erb#L165)
As a result, valuable information about the error is lost. 
In the following example, a failed download of the Installer causes the installation to fail. 
The Installer returns the code 7. However, instead of trying to download the Installer again, the Pre-start script will continue.

```
…
/opt/dynatrace/oneagent is on /var/vcap/data
Extracting...
Warning: S/MIME signature is missing
Unpacking. This may take a few minutes...
Error: Archive is corrupted. Installation aborted.
Setting oneagentwatchdog pid
Installation finished
```

Best regards
	Christoph

**Comment by MartinGoodwell** [comment]
Hi Christoph,
thanks for reaching out.
We'll address this in our next release.
Best regards
Martin

**Comment by lrgar** [comment]
We've implemented checks for the error codes from the installer commands in both the Linux and Windows scripts.
