### ISSUE TITLE
[Question] Support for Bionic Stemcells

### ISSUE THREAD

**Issue by TimGerlach** [Dynatrace/bosh-oneagent-release#59]
Hi Team,
are there plans to test/validate the use of the Dynatrace bosh release with the upcoming Bionic stemcells (April 2021)?

**Comment by arthfl** [comment]
Hi!

Thanks for the pointer.
We'll do a test run to check if everything works as expected and will create follow-ups for adaptions if anything is required :-)

**Comment by TimGerlach** [comment]
Awesome, thank you very much @arthfl!
