### ISSUE TITLE
Please add final release directories to repository

### ISSUE THREAD

**Issue by voelzmo** [Dynatrace/bosh-oneagent-release#8]
Hey,

Could you please add the directories `.final_builds` and `releases` to the github repository? This is necessary for bosh.io to pick it up and display it here http://bosh.io/releases/github.com/dynatrace-innovationlab/bosh-oneagent-release?all=1

**Comment by arthfl** [comment]
Ahoy!

Added the two directories, thanks for the hint @voelzmo :-)
